### PR TITLE
Support rules on .editorconfig files

### PR DESCRIPTION
**Pull request by Corniel**
After some refactorings (#200, #203) is is now possible to implement rules on INI-files and/or `.editorconfig` files. As it turned out that Microsoft also has a [glob implementation](https://learn.microsoft.com/dotnet/core/extensions/file-globbing] I thought, it might be possible to use that dependency (less likely to result in version conflicts for users of our analyzers).

While implementing this rule us MS's implementation, it seems that they accept just everything. :(

### CODE REVIEW

**Review by CptWesley — APPROVED** [review]

**Comment by Corniel** [comment]
@CptWesley With this code we can not invalidate globs. I think that is problematic. What do you think?

**Comment by CptWesley** [comment]
> @CptWesley With this code we can not invalidate globs. I think that is problematic. What do you think?

What do you mean?

**Comment by Corniel** [comment]
Well, by using Microsoft's implementation `*.{exe,bin}}` will not be invalidated, although that is not a valid glob. Other external globs might do that, but I do not want to depend on them. I've an own implementation (#202 ) But is rather slow.

**Comment by CptWesley** [comment]
Shouldn't we validate the same way that microsoft uses them?

**Comment by Corniel** [comment]
> Shouldn't we validate the same way that microsoft uses them?

Well, when deciding how to deal with the values: yes. But when we want to report on issues, we might want to be stricter. But for now, I just removed the rule itself, and *only* provided the framework to define rules, and to be able to read `.editorconfig` files in project files.

**Comment by CptWesley** [comment]
The general editorconfig specs (https://spec.editorconfig.org/) do allow those kind of patterns. I would say that it makes sense to follow the official specification of whatever file format we are dealing with, rather than make it more strict because other tools can't handle it.

**Comment by Corniel** [comment]
I think is not about being able to deal with it, but if someone types: `*.{csproj,vbproj}}` it is most likely, that  `*.{csproj,vbproj}` was intended, instead of matching on either `*.csproj` or `*.vbproj}`. Anyhow, food for thought for PR's to follow.

**Comment by CptWesley** [comment]
Ah I didn't see the double `}`, I thought you wanted to ban `{}`-like expressions because they are not supported by unix shell glob searches

**Pull request merged**
